// 赤矢印
interaction.setStyle('translate',
	new ol.style.Style({
		image: new ol.style.Icon({
			src: 'data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAABQAAAAUCAYAAACNiR0NAAAABmJLR0QA/wD/AP+gvaeTAAAA/ElEQVQ4jcWUvQrCMBSFz1XbRSj4GqKCOFQXN0UtPq7/4OAiDiKo+BqC4NIqcYk1SWtzC4JnCdycftyc3BT4h4Q/9IQ/9DjeAgcWhbSIQlqLelCx+YkDA9CWpb3zoB6dJtfcwBTYW1aoVWEzOIfN4MzxJjLkhv/NWzAN8pgspV1UDMzILEutqCRWKpQ+MMwB6sj63viwKteLCZTtbB0XA9rNbtY5zKt4bESjX46KpSmArnuYauP0vmH3MKnp9ZFQuwOUDOm4vDvPxwjAht+PDtOAMdQVYy7OhCWAAGAaspTm/f70lEyNncQxWcB0aDbMCtShwrHB2Mrzg/25XhpzgW+Y5Ym7AAAAAElFTkSuQmCC'
		})
}));

// 赤回転
interaction.setStyle('rotate',
	new ol.style.Style({
		image: new ol.style.Icon({
			src: 'data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAABQAAAAUCAYAAACNiR0NAAAABmJLR0QA/wD/AP+gvaeTAAACE0lEQVQ4jb3TsWsTYRjH8e/zxlzrogVBpVBcisRQNZdSXHQTmtzSQBQKQaT/goM4ZnLIqtBFoZ0K0kWhVsGhUAUVQrWFVCoUlNqWDhZd2rsk7+NgeiYxJK0tPtt7vM/nnt+978ERl9Qv9Er6hLyb/RmuyZsg+XYgYiN9UNWqjXx1FodKQt7uCwxc75FgHh+LRleCyu49UcZATjW8FDaASaciBVma2W4LlpPeE1WGgV3gNMqqolMirKBiVDgvMALEgS0xNhstvnjdCbxZm+VB9OTOHZmbqzRNKIHrjQqMA91i7PV61NRvtqqrQBEoIjKw8/342RaRtGvh+ZQargG7as20JjI9zfv+qfxEOhe4nvqud/9IwFr8UtlNf9Pa5zOdmtqVgCo8VaQ3uDwcPzT4G9XPACYS6QvBctJLBa6nQdIbOzhpajdFNARtRdYAFOk/KKdoP4CtVtZC0FkcKilsiGpGm+5meyxvBDKCrjsfX5ZCsPZvTgLxwPVG9wuW3fc5IGbFTAj8iQzgVKQAbAmM+4PexU6Yn0xdAh4qbDriF/aeh6AszWyLsVmgWyzzfiKdaxW/dvduiZp5oMuoZKX46kfo/BVjMHVVrZkGzgDLij4TlU8AKhoTZASIKWwa1RvRD7Nv6vtbHoAmMj2BBHcNeluR3sYGXbdiJhzxC/WTtQUb46UvROAcQBW+OAuzy3sH8F/qFwZn1EaMrGbkAAAAAElFTkSuQmCC'
		})
}));
interaction.setStyle('rotate0',
	new ol.style.Style({
		image: new ol.style.Icon({
			src: 'data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAABQAAAAUCAYAAACNiR0NAAAABmJLR0QA/wD/AP+gvaeTAAACE0lEQVQ4jb3TsWsTYRjH8e/zxlzrogVBpVBcisRQNZdSXHQTmtzSQBQKQaT/goM4ZnLIqtBFoZ0K0kWhVsGhUAUVQrWFVCoUlNqWDhZd2rsk7+NgeiYxJK0tPtt7vM/nnt+978ERl9Qv9Er6hLyb/RmuyZsg+XYgYiN9UNWqjXx1FodKQt7uCwxc75FgHh+LRleCyu49UcZATjW8FDaASaciBVma2W4LlpPeE1WGgV3gNMqqolMirKBiVDgvMALEgS0xNhstvnjdCbxZm+VB9OTOHZmbqzRNKIHrjQqMA91i7PV61NRvtqqrQBEoIjKw8/342RaRtGvh+ZQargG7as20JjI9zfv+qfxEOhe4nvqud/9IwFr8UtlNf9Pa5zOdmtqVgCo8VaQ3uDwcPzT4G9XPACYS6QvBctJLBa6nQdIbOzhpajdFNARtRdYAFOk/KKdoP4CtVtZC0FkcKilsiGpGm+5meyxvBDKCrjsfX5ZCsPZvTgLxwPVG9wuW3fc5IGbFTAj8iQzgVKQAbAmM+4PexU6Yn0xdAh4qbDriF/aeh6AszWyLsVmgWyzzfiKdaxW/dvduiZp5oMuoZKX46kfo/BVjMHVVrZkGzgDLij4TlU8AKhoTZASIKWwa1RvRD7Nv6vtbHoAmMj2BBHcNeluR3sYGXbdiJhzxC/WTtQUb46UvROAcQBW+OAuzy3sH8F/qFwZn1EaMrGbkAAAAAElFTkSuQmCC'
		})
}));
